title = "Grace Greater Than Our Sin"
subtitle = "Marvelous Grace of Our Loving Lord"
key_signature = "G"
time_sig_numerator = 3
time_sig_denominator = 4
verse_count = 4
tempo_bpm = 128
phrase_breaks = ["4:48", "8:48", "12:48", "16:48", "20:48", "24:48", "28:48"]
copyrights = [
  "Lyrics: Julia H. Johnston, 1911 (public domain)",
  "Music: 'Moody' by Daniel B. Towner, 1910 (public domain)",
  "Arrangement by OpenPsalm, 2026 and released under the CC-BY 4.0 license",
]

[parts.Soprano]
choral_type = "soprano"
clef = "treble"
staff_number = 1
notes = """
g'4. fis'8 g'4 | a'4 g'4 a'4 | b'2 a'4 | g'2. | fis'4 fis'4 g'4 | a'2 fis'4 | g'4 g'4 a'4 | b'2. | g'4. fis'8 g'4 | a'4 g'4 a'4 | b'2 a'4 | g'2. | a'4. a'8 b'4 | c''4 b'4 a'4 | g'2 fis'4 | g'2. | b'2.@c | g'2. | c''2. | b'2. | a'4. a'8 a'4 | a'4 b'4 a'4 | g'2 c''4 | b'2. | b'2. | g'2. | c''2. | b'2. | a'4. a'8 b'4 | c''4 b'4 a'4 | g'2 fis'4 | g'2.
"""

[parts.Alto]
choral_type = "alto"
clef = "treble"
staff_number = 1
notes = """
d'4. d'8 d'4 | fis'4 e'4 d'4 | d'2 d'4 | d'2. | d'4 d'4 d'4 | fis'2 d'4 | d'4 d'4 d'4 | g'2. | d'4. d'8 d'4 | fis'4 e'4 d'4 | d'2 fis'4 | e'2. | e'4. e'8 g'4 | g'4 g'4 e'4 | d'2 d'4 | d'2. | g'4.@c g'8 g'4 | d'2. | g'4. g'8 g'4 | g'2. | fis'4. fis'8 fis'4 | fis'4 fis'4 d'4 | d'2 g'4 | g'2. | g'4. g'8 g'4 | d'2. | g'4. g'8 g'4 | g'2. | e'4. e'8 g'4 | a'4 g'4 e'4 | d'2 d'4 | d'2.
"""

[parts.Tenor]
choral_type = "tenor"
clef = "bass"
staff_number = 2
notes = """
b4. a8 b4 | c'4 b4 a4 | g2 c'4 | b2. | a4 a4 b4 | c'2 a4 | b4 b4 c'4 | d'2. | b4. a8 b4 | c'4 b4 a4 | g2 c'4 | b2. | c'4. c'8 d'4 | e'4 d'4 c'4 | b2 a4 | b2. | d'2.@c | b2. | e'2. | d'2. | c'4. c'8 c'4 | c'4 d'4 c'4 | b2 e'4 | d'2. | d'2. | b2. | e'2. | d'2. | c'4. c'8 d'4 | e'4 d'4 c'4 | b2 a4 | b2.
"""

[parts.Bass]
choral_type = "bass"
clef = "bass"
staff_number = 2
notes = """
g4. g8 g4 | d4 e4 fis4 | g2 d4 | g2. | d4 d4 d4 | d2 d4 | g4 g4 g4 | <g g,>2. | g4. g8 g4 | d4 e4 fis4 | g2 d4 | e2. | c4. c8 b,4 | a,4 b,4 c4 | d2 d4 | <g g,>2. | g4.@c g8 g4 | g2. | g4. g8 g4 | g2. | d4. d8 d4 | d4 d4 d4 | g2 g4 | g2. | g4. g8 g4 | g2. | g4. g8 g4 | g2. | c4. c8 b,4 | a,4 b,4 c4 | d2 d4 | <g g,>2.
"""

[lyrics.1]
text = "Mar -- ve -- lous grace of our lov -- ing Lord, Grace that ex -- ceeds our sin and our guilt! Yon -- der on Cal -- va -- ry’s mount out -- poured, There where the blood of the Lamb was spilled."

[lyrics.2]
text = "Sin and des -- pair, like the sea waves cold, Threat -- en the soul with in -- fin -- ite loss; Grace that is great -- er, yes, grace un -- told, Points to the ref -- uge, the might -- y cross."

[lyrics.3]
text = "Dark is the stain that we can -- not hide. What can a -- vail to wash it a -- way? Look! There is flow -- ing a crim -- son tide, Bright -- er than snow you may be to -- day."

[lyrics.4]
text = "Mar -- ve -- lous, in -- fin -- ite, match -- less grace, Free -- ly be -- stowed on all who be -- lieve! You that are long -- ing to see His face, Will you this mo -- ment His grace re -- ceive?"

[lyrics.chorus]
text = "Grace, grace, God’s grace, Grace that will par -- don and cleanse with -- in; Grace, grace, God’s grace, Grace that is great -- er than all our sin!"

[parts.Alto.lyrics.chorus]
text = "Mar -- vel -- ous grace, in -- fi -- nite grace, Grace that will par -- don and cleanse with -- in; Mar -- vel -- ous grace, in -- fi -- nite grace, Grace that is great -- er than all our sin!"

[parts.Bass.lyrics.chorus]
text = "Mar -- vel -- ous grace, in -- fi -- nite grace, Grace that will par -- don and cleanse with -- in; Mar -- vel -- ous grace, in -- fi -- nite grace, Grace that is great -- er than all our sin!"
