title = "Nearer, My God, to Thee"
subtitle = ""
tempo_bpm = 95
key_signature = "F"
time_sig_numerator = 4
time_sig_denominator = 4
verse_count = 5
phrase_breaks = ["4:64", "8:64", "12:64", "16:64"]

copyrights = [
  "Lyrics: Sarah F. Adams, 1841 (public domain)",
  "Music: 'Bethany' by Lowell Mason, 1856 (public domain)",
  "Arrangement by OpenPsalm, 2026 and released under the CC-BY 4.0 license"
]

[parts.Soprano]
choral_type = "soprano"
clef = "treble"
staff_number = 1
notes = """
a'2 g'4 f'4 | f'4. d'8 d'2 | c'2 f'4 a'4 | g'1 | a'2 g'4 f'4 | f'4. d'8 d'2 | c'4( f'4) e'4 g'4 | f'1 | c''2 d''4 c''4 | c''4. a'8 c''2 | c''2 d''4 c''4 | c''4. a'8 g'2 | a'2 g'4 f'4 | f'4. d'8 d'2 | c'4( f'4) e'4 g'4 | f'1
"""

[parts.Alto]
choral_type = "alto"
clef = "treble"
staff_number = 1
notes = """
c'2 bes4 a4 | d'4. bes8 bes2 | c'2 c'4 c'4 | c'1 | c'2 bes4 a4 | d'4. bes8 bes2 | a4( c'4) c'4 c'4 | c'1 | f'2 f'4 f'4 | f'4. f'8 f'2 | f'2 f'4 f'4 | g'4. c'8 c'2 | c'2 bes4 a4 | d'4. bes8 bes2 | a4( c'4) c'4 c'4 | c'1
"""

[parts.Tenor]
choral_type = "tenor"
clef = "bass"
staff_number = 2
notes = """
f2 e4 f4 | bes4. f8 f2 | a2 f4 f4 | e1 | f2 e4 f4 | bes4. f8 f2 | f4( a4) g4 bes4 | a1 | a2 bes4 a4 | a4. c'8 a2 | a2 bes4 a4 | g4. f8 e2 | f2 e4 f4 | bes4. f8 f2 | f4( a4) g4 bes4 | a1
"""

[parts.Bass]
choral_type = "bass"
clef = "bass"
staff_number = 2
notes = """
f2 c4 d4 | bes,4. bes,8 bes,2 | f,2 a,4 f,4 | c1 | f2 c4 d4 | bes,4. bes,8 bes,2 | f4( a4) c4 c4 | f,1 | f2 f4 f4 | f4. f8 f2 | f2 bes,4 f4 | e4. f8 c2 | f2 c4 d4 | bes,4. bes,8 bes,2 | f4( a4) c4 c4 | f,1
"""

[lyrics.1]
text = """
Near -- er, my God, to thee, near -- er to thee!
E'en though it be a cross that rais -- eth me,
still all my song shall be,
near -- er, my God, to thee;
near -- er, my God, to thee, near -- er to thee!
"""

[lyrics.2]
text = """
Though like the wan -- der -- er, the sun gone down,
dark -- ness be o -- ver me, my rest a stone;
yet in my dreams I'd be
near -- er, my God, to thee;
near -- er, my God, to thee, near -- er to thee!
"""

[lyrics.3]
text = """
There let the way ap -- pear, steps un -- to heav'n;
all that thou send -- est me, in mer -- cy giv'n;
an -- gels to beck -- on me
near -- er, my God, to thee;
near -- er, my God, to thee, near -- er to thee!
"""

[lyrics.4]
text = """
Then, with my wak -- ing thoughts bright with thy praise,
out of my ston -- y griefs Beth -- el I'll raise;
so by my woes to be
near -- er, my God, to thee;
near -- er, my God, to thee, near -- er to thee!
"""

[lyrics.5]
text = """
Or if, on joy -- ful wing cleav -- ing the sky,
sun, moon, and stars for -- got, up -- ward I fly,
still all my song shall be,
near -- er, my God, to thee;
near -- er, my God, to thee, near -- er to thee!
"""
