title = "Hark, Hark, My Soul"
subtitle = ""
verse_count = 5
key_signature = "D"
time_sig_numerator = 4
time_sig_denominator = 4
tempo_bpm = 100
phrase_breaks = ["4:64", "8:64", "12:64", "16:64", "20:64", "24:64"]
copyrights = [
  "Lyrics: Frederick W. Faber, 1854 (public domain)",
  "Music: George H. Crosby, 1929 (public domain)",
  "Arrangement by OpenPsalm, 2026 and released under the CC-BY 4.0 license",
]

[parts.Soprano]
choral_type = "soprano"
clef = "treble"
staff_number = 1
notes = """
fis'2 fis'4. fis'8 | a'2. a'4 | g'4 fis'4 b'4 b'4 | a'2 a'2 | b'2 cis''4 cis''4 | d''2. a'4 | g'4 g'4 fis'4 fis'4 | e'1 | fis'2 a'4. a'8 | d''2. d''4 | d''4 b'4 cis''4 d''4 | e''4.( d''8) cis''2 | d''2 a'4 b'4 | cis''2. e'4 | fis'4 fis'4 gis'4 gis'4 | a'1 | a'2@c a'4 a'4 | a'2 a'4( d''4) | d''2 d''4 d''4 | d''1 | fis''2 cis''4 d''4 | e''4( d''4) cis''4 b'4 | a'4 a'4 e''4. d''8 | d''1!
"""

[parts.Alto]
choral_type = "alto"
clef = "treble"
staff_number = 1
notes = """
d'2 d'4. d'8 | e'2. d'4 | d'4 d'4 g'4 g'4 | d'2 d'2 | g'2 e'4 e'4 | d'2. fis'4 | e'4 e'4 d'4 d'4 | cis'1 | d'2 e'4. e'8 | fis'2. fis'4 | e'4 e'4 e'4 e'4 | e'2 e'2 | d'2 d'4 d'4 | e'2. cis'4 | d'4 d'4 d'4 d'4 | cis'1 | d'2@c cis'4 cis'4 | d'2 d'2 | d'2 d'4 d'4 | d'1 | a'2 a'4 a'4 | g'2 g'4 g'4 | fis'4 fis'4 g'4. g'8 | fis'1!
"""

[parts.Tenor]
choral_type = "tenor"
clef = "bass"
staff_number = 2
notes = """
a2 a4. a8 | a2. fis4 | g4 a4 d'4 d'4 | a4.( g8) fis4( a4) | d'2 a4 a4 | a2. c'4 | b8[ bes8] a4 a4 a4 | a1 | a2 a4. a8 | b2. b4 | b4 gis4 a4 b4 | cis'4.( b8) a2 | a2 a4 a4 | a2. a4 | gis4 gis4 b4 b4 | a1 | fis4@c( a4) g4 b4 | a4.( g8) fis4( a4) | b4( d'4) cis'4 b4 | a4.( g8 fis2) | d'2 a4 d'4 | b2 b4 d'4 | d'4 d'4 cis'4. a8 | a1!
"""

[parts.Bass]
choral_type = "bass"
clef = "bass"
staff_number = 2
notes = """
d2 d4. d8 | cis2. c4 | b,4 a,4 g,4 g4 | fis4.( e8) d4( fis4) | g2 g4 g4 | fis2. dis4 | e4 cis4 d4 fis4 | a4( g4 fis4 e4) | d2 cis4. cis8 | b,2. b,4 | e4 d4 cis4 b,4 | a,2 a,4( g4) | fis2 fis4 f4 | e2. e4 | e4 e4 e4 e4 | a,4( g4 fis4 e4) | d4@c( fis4) e4 g4 | fis4.( e8) d4( fis4) | g4( b4) a4 g4 | fis4.( e8 d2) | d2 e4 fis4 | g2 g4 g4 | a4 a4 a,4. d8 | d1!
"""

[lyrics.1]
text = "Hark, hark, my soul! an -- gel -- ic songs are swell -- ing O'er earth's green fields and o -- cean's wave- -- beat shore: How sweet the truth those bless -- ed strains are tell -- ing Of that new life when sin shall be no more!"

[lyrics.2]
text = "On -- ward we go, for still we hear them sing -- ing, \"Come, wea -- ry souls, for Je -- sus bids you come\"; And through the dark, its ech -- oes sweet -- ly ring -- ing, The mu -- sic of the gos -- pel leads us home."

[lyrics.3]
text = "Far, far a -- way, like bells at eve -- ning peal -- ing, The voice of Je -- sus sounds o'er land and sea; And la -- den souls, by thou -- sands meek -- ly steal -- ing, Kind Shep -- herd, turn their wea -- ry steps to Thee."

[lyrics.4]
text = "Rest comes at length; though life be long and drear -- y, The day must dawn, and dark -- some night be past; Faith's jour -- ney ends in wel -- come to the wea -- ry, And heav'n, the heart's true home, will come at last."

[lyrics.5]
text = "An -- gels, sing on! your faith -- ful watch -- es keep -- ing, Sing us sweet frag -- ments of the songs a -- bove; Till morn -- ing's joy shall end the night of weep -- ing, And life's long shad -- ows break in cloud -- less love."

[lyrics.chorus]
text = "An -- gels of Je -- sus, an -- gels of light, Sing -- ing to wel -- come the pil -- grims of the night!"
