title = "For Christ and the Church"
subtitle = ""
key_signature = "D"
time_sig_numerator = 4
time_sig_denominator = 4
tempo_bpm = 100
verse_count = 4
phrase_breaks = ["3:48", "5:48", "7:56", "9:48", "13:48"]
optional_phrase_breaks = ["11:48", "15:48"]
non_breaking_phrase_breaks = ["10:44", "12:44", "14:44"]
copyrights = [
  "Lyrics: Eliza E. Hewitt, 1890 (public domain)",
  "Music: William J. Kirkpatrick, 1890 (public domain)",
  "Arrangement by OpenPsalm, 2026 and released under the CC-BY 4.0 license",
]

[parts.Soprano]
choral_type = "soprano"
clef = "treble"
staff_number = 1
notes = """
s2 s4 a'4 | a'4 fis'8. g'16 a'4 fis'8 e'8 | d'4 d'4 d''4 cis''8 b'8 |
a'4 a'8. b'16 a'4 g'8 fis'8 | fis'4 e'8 d'8 e'4! a'8 g'8 | fis'4 fis'8. e'16 d'4 fis'8 g'8 |
a'4 d''4 d''4. a'8 | b'4 d''8. b'16 a'4 d'8 g'8 | fis'4 e'8. e'16 d'4! a'4@c |
cis''2~ cis''8. cis''16 b'8. cis''16 | d''2 a'4 a'4 | b'2~ b'8. d''16 cis''8. b'16 |
a'2. a'8. a'16 | d''2~ d''8. d''16 cis''8. d''16 | e''4 d''2 b'4 |
a'4. a'8 b'4 cis''4 | d''2. s4
"""

[parts.Alto]
choral_type = "alto"
clef = "treble"
staff_number = 1
notes = """
s2 s4 fis'4 | fis'4 d'8. e'16 fis'4 d'8 d'8 | d'4 d'4 fis'4 a'8 g'8 |
fis'4 fis'8. g'16 fis'4 e'8 d'8 | d'4 b8 b8 cis'4! cis'8 e'8 | d'4 d'8. cis'16 d'4 d'8 e'8 |
fis'4 fis'4 fis'4. fis'8 | g'4 g'8. g'16 fis'4 d'8 d'8 | d'4 cis'8. cis'16 d'4! a'4@c |
g'2~ g'8. g'16 g'8. g'16 | fis'2 fis'4 fis'4 | g'2~ g'8. b'16 a'8. g'16 |
fis'2. fis'8. fis'16 | fis'2~ fis'8. fis'16 g'8. a'16 | g'4 g'2 g'4 |
fis'4. fis'8 g'4 g'4 | fis'2. s4
"""

[parts.Tenor]
choral_type = "tenor"
clef = "bass"
staff_number = 2
notes = """
s2 s4 d'4 | d'4 a8. a16 d'4 a8 g8 | fis4 fis4 a4 d'8 d'8 |
d'4 d'8. d'16 d'4 a8 a8 | b4 gis8 gis8 a4! e8 a8 | a4 a8. g16 fis4 a8 a8 |
d'4 a4 a4. d'8 | d'4 b8. d'16 d'4 a8 b8 | a4 g8. g16 fis4! r4@c |
r4 e'4 e'8. e'16 e'8. a16 | a2 d'4 r4 | r4 d'4 d'8. d'16 d'8. d'16 |
d'2. r4 | r4 a8. a16 a8. a16 a8. a16 | b4 b2 d'4 |
d'4. d'8 cis'4 a4 | a2. s4
"""

[parts.Bass]
choral_type = "bass"
clef = "bass"
staff_number = 2
notes = """
s2 s4 d4 | d4 d8. d16 d4 d8 d8 | d4 d4 d4 d8 d8 |
d4 d8. d16 d4 cis8 d8 | b,4 e8 e8 a,4! a,8 cis8 | d4 d8. d16 d4 d8 d8 |
d4 d4 d4. d8 | g4 g8. g16 d4 fis8 g8 | a4 a,8. a,16 d4! r4@c |
r4 a4 a8. a16 a8. a16 | d2 d4 r4 | r4 g4 g8. g16 g8. g16 |
d2. r4 | r4 d8. d16 d8. d16 e8. fis16 | g4 g2 g4 |
a4. a8 a4 a,4 | d2. s4
"""

[lyrics.1]
text = "“For Christ and the Church,” let our voic -- es ring, Let us hon -- or the name of our own bless -- èd King; Let us work with a will in the strength of youth, And loy -- al -- ly stand for the king -- dom of truth."

[lyrics.2]
text = "“For Christ and the Church,” be our ear -- nest prayer, Let us fol -- low His ban -- ner, the cross dai -- ly bear; Let us yield, whol -- ly yield, to His Spir -- it’s power, And serve faith -- ful -- ly ev -- 'ry day, ev -- 'ry hour."

[lyrics.3]
text = "“For Christ and the Church,” will -- ing of -- f'rings make, Time and tal -- ents and gold, for the dear Mas -- ter’s sake; We will ren -- der the best we can bring to Him, The heart’s wealth of love, that will nev -- er grow dim."

[lyrics.4]
text = "“For Christ and the Church,” let us cast a -- side, By His con -- quer -- ing grace, chains of self, fear, and pride; May our lives be en -- riched by an aim so grand; Then hap -- py the call to the Sav -- ior’s right hand."

[lyrics.chorus]
text = "For Christ our dear Re -- deem -- er, For Christ the cru -- ci -- fied; For the Church His blood hath pur -- chased, The church, His ho -- ly bride.."
