title = "Summer Land"
subtitle = "Beyond This Land of Parting"
key_signature = "G"
time_sig_numerator = 4
time_sig_denominator = 4
tempo_bpm = 96
verse_count = 4
phrase_breaks = ["3:64", "5:48", "7:64", "9:48", "11:48", "13:48", "15:48"]
non_breaking_phrase_breaks = ["10:40", "12:40", "14:40"]
copyrights = [
  "Lyrics: M. B. C. Slade, 1876 (public domain)",
  "Music: Asa Brooks Everett, 1876 (public domain)",
  "Arrangement by OpenPsalm, 2026 and released under the CC-BY 4.0 license"
]

[parts.Soprano]
choral_type = "soprano"
clef = "treble"
staff_number = 1
notes = """
s2. d'4 | g'8 g'8 g'8 g'8 g'4 b'4 | d''4 d''8 e''8 d''4 b'4 | a'8 a'8 a'8 a'8 a'4 d''4 | b'4 b'8 c''8 b'4 d'4 | g'8 g'8 g'8 g'8 g'4 b'4 | d''4 d''8 e''8 d''4 b'4 | a'8 a'8 a'8 a'8 b'4 a'4 | g'2. g'8@c fis'8 | e'2~ e'8 fis'8 g'8 e'8 | d'2. g'8 a'8 | b'2~ b'8 c''8 d''8 b'8 | a'2. b'8 d''8 | e''2~ e''8 c''8 c''8 e''8 | d''2. b'4 | a'8 a'8 a'8 a'8 b'4 a'4 | g'2. s4
"""

[parts.Alto]
choral_type = "alto"
clef = "treble"
staff_number = 1
notes = """
s2. b4 | d'8 d'8 d'8 d'8 d'4 g'4 | g'4 g'8 g'8 g'4 g'4 | fis'8 fis'8 fis'8 fis'8 fis'4 fis'4 | g'4 g'8 g'8 g'4 b4 | d'8 d'8 d'8 d'8 d'4 g'4 | g'4 g'8 g'8 g'4 g'4 | fis'8 fis'8 fis'8 fis'8 g'4 d'4 | d'2. b8@c d'8 | c'2~ c'8 d'8 e'8 c'8 | b2. b8 d'8 | g'2~ g'8 a'8 b'8 g'8 | fis'2. g'8 g'8 | g'2~ g'8 e'8 e'8 g'8 | g'2. g'4 | fis'8 fis'8 fis'8 fis'8 g'4 d'4 | d'2. s4
"""

[parts.Tenor]
choral_type = "tenor"
clef = "bass"
staff_number = 2
notes = """
s2. g4 | b8 b8 b8 b8 b4 d'4 | b4 b8 c'8 b4 d'4 | d'8 d'8 d'8 d'8 d'4 d'4 | d'4 d'8 e'8 d'4 g4 | b8 b8 b8 b8 b4 d'4 | b4 b8 c'8 b4 d'4 | d'8 d'8 d'8 d'8 d'4 c'4 | b2. r4@c | g4 g4 g8 g8 g8 g8 | g2. r4 | d'4 d'4 d'8 d'8 d'8 d'8 | d'2. r4 | c'4 c'4 c'8 g8 g8 c'8 | b2. d'4 | d'8 d'8 d'8 d'8 d'4 c'4 | b2. s4
"""

[parts.Bass]
choral_type = "bass"
clef = "bass"
staff_number = 2
notes = """
s2. g4 | g8 g8 g8 g8 g4 g4 | g4 g8 g8 g4 g4 | d8 d8 d8 d8 d4 d4 | g4 g8 g8 g4 g4 | g8 g8 g8 g8 g4 g4 | g4 g8 g8 g4 g4 | d8 d8 d8 d8 d4 d4 | g2. r4@c | c4 c4 c8 c8 c8 c8 | g,2. r4 | g4 g4 g8 g8 g8 g8 | d2. r4 | c4 c4 c8 c8 c8 c8 | g2. g4 | d8 d8 d8 d8 d4 d4 | g2. s4
"""

[lyrics.1]
text = "Be -- yond this land of part -- ing, los -- ing and leav -- ing, Far be -- yond the loss -- es, dark -- en -- ing this, And far be -- yond the tak -- ing and the be -- reav -- ing Lies the sum -- mer land of bliss."

[lyrics.2]
text = "Be -- yond this land of toil -- ing, sow -- ing and reap -- ing, Far be -- yond the sha -- dows, dark -- en -- ing this, And far be -- yond the sigh -- ing, moan -- ing and weep -- ing, Lies the sum -- mer land of bliss."

[lyrics.3]
text = "Be -- yond this land of sin -- ning, faint -- ing and fail -- ing, Far be -- yond the doubt -- ings, dark -- en -- ing this, And far be -- yond the griefs and dan -- gers be -- fall -- ing, Lies the sum -- mer land of bliss."

[lyrics.4]
text = "Be -- yond this land of wait -- ing, seek -- ing and sigh -- ing, Far be -- yond the sor -- rows, dark -- en -- ing this, And far be -- yond the pain and sick -- ness and dy -- ing Lies the sum -- mer land of bliss."

[lyrics.chorus]
text = "Land be -- yond, so fair and bright! Land be -- yond, where is no night! Sum -- mer land, God is its Light. O hap -- py sum -- mer land of bliss!"
