title = "Come, Thou Fount of Every Blessing"
subtitle = ""
copyrights = [
  "Lyrics: Robert Robinson, 1758 (public domain)",
  "Music: Repository of Sacred Music Part Second, 1813 (public domain)",
  "Adaptation: Jon Hood, 2026 and released to the public domain under the CC-0",
  "Arrangement by OpenPsalm, 2026 and released under the CC-BY 4.0 license",
]
key_signature = "Eb"
time_sig_numerator = 3
time_sig_denominator = 4
tempo_bpm = 100
verse_count = 5
optional_phrase_breaks = ["3:32", "7:32", "11:32", "15:32"]
phrase_breaks = ["5:32", "9:32", "13:32"]
commentary = "<p>For more information on the life and theological journey of the author, Robert Robinson, see the <a href=\"/blog/20260409-robert-robinson\">Prone to Wander</a> blog article.</p>"

[parts.Soprano]
choral_type = "soprano"
clef = "treble"
staff_number = 1
notes = """
s2 g'8 f'8 | ees'4 ees'4 g'8 bes'8 | f'4 f'4 g'8 bes'8 | c''4 bes'4 g'8 f'8 |
ees'2 g'8 f'8 | ees'4 ees'4 g'8 bes'8 | f'4 f'4 g'8 bes'8 | c''4 bes'4 g'8 f'8 |
ees'2 bes'8 c''16[ d''16] | ees''4 d''4 c''8 bes'8 | c''8[ bes'8] g'4 bes'8 c''16[ d''16] | ees''4 d''4 c''8 bes'8 |
ees''2 g'8 f'8 | ees'4 ees'4 g'8 bes'8 | f'4 f'4 g'8 bes'8 | c''4 bes'4 g'8 f'8 |
ees'2 s4 |
"""

[parts.Alto]
choral_type = "alto"
clef = "treble"
staff_number = 1
notes = """
s2 ees'8 d'8 | ees'4 ees'4 ees'8 ees'8 | d'4 d'4 ees'8 ees'8 | ees'4 ees'4 ees'8 d'8 |
ees'2 ees'8 d'8 | ees'4 ees'4 ees'8 ees'8 | d'4 d'4 ees'8 ees'8 | ees'4 ees'4 ees'8 d'8 |
ees'2 ees'8 aes'8 | g'4 bes'4 aes'8 g'8 | ees'4 ees'4 ees'8 aes'8 | g'4 bes'4 aes'8 g'8 |
g'2 ees'8 d'8 | ees'4 ees'4 ees'8 ees'8 | d'4 d'4 ees'8 ees'8 | ees'4 ees'4 ees'8 d'8 |
ees'2 s4 |
"""

[parts.Tenor]
choral_type = "tenor"
clef = "bass"
staff_number = 2
notes = """
s2 bes8 aes8 | g4 g4 bes8 bes8 | bes4 bes4 bes8 bes8 | aes4 g4 bes8 aes8 |
g2 bes8 aes8 | g4 g4 bes8 bes8 | bes4 bes4 bes8 bes8 | aes4 g4 bes8 aes8 |
g2 bes8 aes8 | bes4 bes4 ees'8 ees'8 | aes8[ g8] bes4 bes8 aes8 | bes4 bes4 ees'8 ees'8 |
bes2 bes8 aes8 | g4 g4 bes8 bes8 | bes4 bes4 bes8 bes8 | aes4 g4 bes8 aes8 |
g2 s4 |
"""

[parts.Bass]
choral_type = "bass"
clef = "bass"
staff_number = 2
notes = """
s2 ees8 bes,8 | ees4 ees4 ees8 g,8 | bes,4 bes,4 ees8 g8 | aes4 ees4 bes,8 bes,8 |
ees2 ees8 bes,8 | ees4 ees4 ees8 g,8 | bes,4 bes,4 ees8 g8 | aes4 ees4 bes,8 bes,8 |
ees2 g8 f8 | ees4 g4 aes8 ees8 | ees4 ees4 g8 f8 | ees4 g4 aes8 ees8 |
ees2 ees8 bes,8 | ees4 ees4 ees8 g,8 | bes,4 bes,4 ees8 g8 | aes4 ees4 bes,8 bes,8 |
ees2 s4 |
"""

[lyrics.1]
text = "Come, Thou Fount of eve -- ry bless -- ing, Tune my heart to sing Thy grace; Streams of mer -- cy, nev -- er ceas -- ing, Call for songs of loud -- est praise. Teach me some mel -- o -- dious son -- net, Sung by flam -- ing tongues a -- bove. Look! The mount, I’m fixed up -- on it, Mount of God’s un -- chang -- ing love."

[lyrics.2]
text = "Sor -- r'wing I shall be in spi -- rit, Till re -- leased from flesh and sin, Yet from what I do in -- her -- it, Here Thy prais -- es I’ll be -- gin; Here I raise my Eb -- e -- nee -- zer; Here by Thy great help I’ve come; And I hope, by Thy good plea -- sure, Safe -- ly to ar -- rive at home."

[lyrics.3]
text = "Je -- sus sought me when a stran -- ger, Wan -- d’ring from the fold of God; He, to res -- cue me from dan -- ger, In -- ter -- posed His pre -- cious blood; How His kind -- ness yet pur -- sues me Mor -- tal tongue can nev -- er tell, Clothed in flesh, till death shall loose me I can -- not pro -- claim it well."

[lyrics.4]
text = "O to grace how great a debt -- or Dai -- ly I’m con -- strained to be! Let Thy good -- ness, like a fet -- ter, Bind my wan -- d’ring heart to Thee. Prone to wan -- der, Lord, I feel it, Prone to leave the God I love; Here’s my heart, O take and seal it, Seal it for Thy courts a -- bove."

[lyrics.5]
text = "O that day when freed from sin -- ning, I shall see Thy love -- ly face; Ar -- rayed then in blood washed lin -- en How I’ll sing Thy sov -- ’reign grace; Come, my Lord, no long -- er tar -- ry, Take my ran -- somed soul a -- way; Send Thine an -- gels now to car -- ry Me to realms of end -- less day."
