title = "On Calvary's Cross, Behold the One"
subtitle = ""
copyrights = [
  "Lyrics: Anonymous, obtained from Messages of Love Hymn Book, 1920 (public domain)",
  "Music: 'Hamburg' by Lowell Mason, 1824 (public domain)",
  "Arrangement by OpenPsalm, 2026 and released under the CC-BY 4.0 license"
]
phrase_breaks = ["4:48", "8:48", "12:48"]
key_signature = "G"
time_sig_numerator = 4
time_sig_denominator = 4
tempo_bpm = 120
verse_count = 4

[parts.Soprano]
choral_type = "soprano"
clef = "treble"
staff_number = 1
notes = """
g'2 g'4 a'4 | b'2 a'4( b'4) | c''2 b'4( a'4) | b'2. r4 |
b'2 b'4 b'4 | c''2 b'4( a'4) | g'2 fis'4( g'4) | a'2. r4 |
g'2 g'4 a'4 | b'2 a'4( b'4) | c''2 b'4( a'4) | b'2. r4 |
b'2 b'4 b'4 | a'2 g'2 | a'2 b'4( a'4) | g'1 |
"""

[parts.Alto]
choral_type = "alto"
clef = "treble"
staff_number = 1
notes = """
d'2 d'4 fis'4 | g'2 a'4( gis'4) | a'2 g'4( fis'4) | g'2. r4 |
g'2 g'4 g'4 | g'2 g'4( fis'4) | g'2 d'2 | fis'2. r4 |
d'2 d'4 fis'4 | g'2 a'4( gis'4) | a'2 g'4( fis'4) | g'2. r4 |
g'2 g'4 g'4 | fis'2 e'2 | g'2 fis'2 | g'1 |
"""

[parts.Tenor]
choral_type = "tenor"
clef = "bass"
staff_number = 2
notes = """
b2 b4 d'4 | d'2 e'2 | e'2 d'2 | d'2. r4 |
d'2 d'4 d'4 | e'2 d'2 | d'2 c'4( b4) | d'2. r4 |
b2 b4 d'4 | d'2 e'2 | e'2 d'2 | d'2. r4 |
d'2 d'4 d'4 | d'4( c'4) b2 | e'2 d'4( c'4) | b1 |
"""

[parts.Bass]
choral_type = "bass"
clef = "bass"
staff_number = 2
notes = """
g2 g4 d4 | g2 c'4( b4) | a2 d2 | g2. r4 |
g2 g4 g4 | g2 g4( c'4) | b2 a4( g4) | d2. r4 |
g2 g4 d4 | g2 c'4( b4) | a2 d2 | g2. r4 |
g2 g4 g4 | d2 e2 | c2 d2 | g,1 |
"""

[lyrics.1]
text = "On Cal -- v’ry’s cross, be -- hold the One Who is God’s Fel -- low and His Son, Ac -- curs -- ed there up -- on the tree, He died to set the guilt -- y free."

[lyrics.2]
text = "He “knew no sin,” yet He must there God’s right -- eous, ho -- ly judg -- ment bear, Must suf -- fer in our guilt -- y stead, And num -- bered be a -- mong the dead."

[lyrics.3]
text = "He’s ris -- en now, the work is done, And God has glo -- ri -- fied His Son; Has set Him in the high -- est place, The source of rich, un -- bound -- ed grace."

[lyrics.4]
text = "Then to the Lord for ref -- uge fly, For why, poor sin -- ner, wilt thou die? Why wilt thou still re -- fuse His call? Who seeks to save, who died for all."
