title = "Now the Day is Over"
verse_count = 8
key_signature = "A"
time_sig_numerator = 4
time_sig_denominator = 4
tempo_bpm = 110
phrase_breaks = ["4:64"]
copyrights = [
  "Lyrics: Sabine Baring-Gould, 1865 (public domain)",
  "Music: 'Merrial' by Joseph Barnby, 1868 (public domain)",
  "Arrangement by OpenPsalm, 2026 and released under the CC-BY 4.0 license",
]
optional_phrase_breaks = ["2:64", "6:64"]
non_breaking_phrase_breaks = ["5:64", "7:48"]

[lyrics.1]
text = "Now the day is o -- ver, Night is draw -- ing nigh, Sha -- dows of the eve -- ning Steal a -- cross the sky."

[lyrics.2]
text = "Now the dark -- ness gath -- ers, Stars be -- gin to peep, Birds, and beasts and flow -- ers Soon will be a -- sleep."

[lyrics.3]
text = "Je -- sus, give the wea -- ry Calm and sweet re -- pose; With Thy tend' -- rest bless -- ing May mine eye -- lids close."

[lyrics.4]
text = "Grant to lit -- tle chil -- dren Vi -- sions bright of Thee; Guard the sail -- ors toss -- ing On the deep, blue sea."

[lyrics.5]
text = "Com -- fort those who suf -- fer, Watch -- ing late in pain; Those who plan some e -- vil From their sin re -- strain."

[lyrics.6]
text = "Through the long night watch -- es May Thine an -- gels spread Their white wings a -- bove me, Watch -- ing round my bed."

[lyrics.7]
text = "When the morn -- ing wak -- ens, Then may I a -- rise Pure, and fresh, and sin -- less In Thy ho -- ly eyes."

[lyrics.8]
text = "Glo -- ry to the Fa -- ther, Glo -- ry to the Son, And to Thee, blest Spir -- it, While all a -- ges run."

[parts.Soprano]
choral_type = "soprano"
clef = "treble"
staff_number = 1
notes = """
e'4 e'4 e'4 e'4 | e'2 e'2 | fis'4 fis'4 eis'4 fis'8[ gis'8] | fis'2( a'2) |
a'4. a'8 gis'4 fis'4 | e'2 e'2 | e'4. e'8 e'4 e'4 | e'1
"""

[parts.Alto]
choral_type = "alto"
clef = "treble"
staff_number = 1
notes = """
cis'4 cis'4 b4 cis'8[ d'8] | cis'2 cis'2 | cis'4 cis'4 cis'4 cis'4 | cis'1 |
cis'4. cis'8 dis'4 dis'4 | e'2 e'2 | d'4. d'8 d'4 d'4 | cis'1
"""

[parts.Tenor]
choral_type = "tenor"
clef = "bass"
staff_number = 2
notes = """
a4 a4 gis4 gis4 | a2 a2 | a4 a4 gis4 b4 | a4( cis'4 fis'4 e'4) |
dis'4. fis8 b4 a4 | gis2 a2 | a4 gis4/+24 fis4 gis4 | a1
"""

[parts.Bass]
choral_type = "bass"
clef = "bass"
staff_number = 2
suppress_verses = [2, 3, 4, 5, 6, 7, 8]
suppress_verses_when = ["soprano", "alto", "tenor"]

notes = """
a4 e4 gis4 e4 | a4( e4) cis4( a,4) | fis,4 a,4 cis4 cis4 | fis1 |
b,4. b,8 b,4 b,4 | e4 d4 cis4 c4 | b,2. b,4 | a,1
"""
