title = "In the Service of the King"
subtitle = ""
verse_count = 4
key_signature = "Bb"
time_sig_numerator = 4
time_sig_denominator = 4
tempo_bpm = 104
phrase_breaks = ["5:48", "9:48", "13:48"]
copyrights = [
  "Lyrics: Alfred H. Ackley, 1912 (public domain)",
  "Music: B. D. Ackley, 1912 (public domain)",
  "Arrangement by OpenPsalm, 2026 and released under the CC-BY 4.0 license",
]
optional_phrase_breaks = ["3:48", "7:48", "11:48", "15:32"]

[parts.Soprano]
choral_type = "soprano"
clef = "treble"
staff_number = 1
notes = """
s2. d'8. ees'16 | f'8. f'16 e'8. f'16 g'8. f'16 e'8. f'16 | d''2. d''8 ees''8 | d''4 c''4 f'4 d''4 | c''4 bes'2 d'8. ees'16 | f'8. f'16 e'8. f'16 g'8. f'16 e'8. f'16 | d''2. d''8 ees''8 | d''4 c''4 g'4 a'4 | bes'2. f'8@c bes'8 | d''4 d''4 ees''4 d''4 | g'2. a'8 bes'8 | c''4 a'4 bes'4 c''4 | d''2. d''8 ees''8 | f''4 d''4 ees''4 d''4 | c''4 bes'4 a'4 g'4 | f'8 d''4. d''4. c''8 | bes'2. s4
"""

[parts.Alto]
choral_type = "alto"
clef = "treble"
staff_number = 1
notes = """
s2. bes8. c'16 | d'8. d'16 cis'8. d'16 d'8. d'16 cis'8. d'16 | f'2. f'8 g'8 | f'4 ees'4 ees'4 f'4 | ees'4 d'2 bes8. c'16 | d'8. d'16 cis'8. d'16 d'8. d'16 cis'8. d'16 | f'2. f'8 g'8 | f'4 ees'4 ees'4 ees'4 | d'2. d'8@c d'8 | f'4 f'4 g'4 f'4 | e'2. ees'8 d'8 | ees'4 f'4 f'4 f'4 | f'2. f'8 f'8 | f'4 f'4 g'4 f'4 | ees'4 ees'4 ees'4 cis'4 | d'8 f'4. f'4. ees'8 | d'2. s4
"""

[parts.Tenor]
choral_type = "tenor"
clef = "bass"
staff_number = 2
notes = """
s2. f8. f16 | bes8. bes16 bes8. bes16 bes8. bes16 bes8. bes16 | bes2. bes8 bes8 | a4 a4 a4 a4 | a4 bes2 f8. f16 | bes8. bes16 bes8. bes16 bes8. bes16 bes8. bes16 | bes2. bes8 bes8 | a4 a4 bes4 c'4 | bes2. bes8@c f8 | bes4 bes4 bes4 bes4 | bes2. c'8 bes8 | a4 c'4 bes4 a4 | bes2. bes8 c'8 | d'4 bes4 bes4 bes4 | g4 g4 a4 bes4 | bes8 bes4. a4. a8 | f2. s4
"""

[parts.Bass]
choral_type = "bass"
clef = "bass"
staff_number = 2
notes = """
s2. bes,8. bes,16 | bes,8. bes,16 bes,8. bes,16 bes,8. bes,16 bes,8. bes,16 | bes2. bes8 bes8 | f4 f4 f4 f4 | f4 bes,2 bes,8. bes,16 | bes,8. bes,16 bes,8. bes,16 bes,8. bes,16 bes,8. bes,16 | bes2. bes8 bes8 | f4 f4 f4 f4 | bes,2. bes,8@c bes,8 | bes,4 bes,4 bes,4 bes,4 | c2. f8 f8 | f4 ees4 d4 f4 | bes2. bes8 bes8 | bes4 bes,4 bes,4 bes,4 | ees4 ees4 ees4 e4 | f8 f4. f4. f8 | bes,2. s4
"""

[lyrics.1]
text = "I am hap -- py in the ser -- vice of the King, I am hap -- py, Oh so hap -- py! I have peace and joy that noth -- ing else can bring, In the ser -- vice of the King."

[lyrics.2]
text = "I am hap -- py in the ser -- vice of the King, I am hap -- py, Oh so hap -- py! Through the sun -- shine and the shad -- ow I can sing, In the ser -- vice of the King."

[lyrics.3]
text = "I am hap -- py in the ser -- vice of the King, I am hap -- py, Oh so hap -- py! To His guid -- ing hand for -- ev -- er I will cling, In the ser -- vice of the King."

[lyrics.4]
text = "I am hap -- py in the ser -- vice of the King, I am hap -- py, Oh so hap -- py! All that I pos -- sess to Him I glad -- ly bring, In the ser -- vice of the King."

[lyrics.chorus]
text = "In the ser -- vice of the King, Ev -- ery tal -- ent I will bring; I have peace and joy and bless -- ing In the ser -- vice of the King."
