title = "Almost Persuaded"
copyrights = [
  "Lyrics and Music: Philip P. Bliss, 1871 (public domain)",
  "Arrangement by OpenPsalm, 2026 and released under the CC-BY 4.0 license"
]
key_signature = "G"
time_sig_numerator = 6
time_sig_denominator = 8
tempo_bpm = 110
verse_count = 3
phrase_breaks = ["4:48", "8:48", "10:48", "12:48", "14:48"]

[parts.Soprano]
choral_type = "soprano"
clef = "treble"
staff_number = 1
notes = """
b'4. c''4 c''8 | b'4. g'4. | g'4. a'4 a'8 | b'2. | b'4. c''4 c''8 | b'4. g'4. | a'4. b'4 a'8 | g'2. | c''4. c''4 c''8 | c''4 b'8 b'4. | d''4. a'4 c''8 | c''4 b'8 b'4. | g'4. g'4 g'8 | g'4 a'8 b'4. | b'4. b'4! a'8 | g'2.
"""

[parts.Alto]
choral_type = "alto"
clef = "treble"
staff_number = 1
notes = """
d'4. e'4 e'8 | d'4. b4. | e'4. fis'4 fis'8 | g'2. | d'4. e'4 e'8 | d'4. b4. | d'4. d'4 c'8 | b2. | e'4. e'4 e'8 | e'4 d'8 d'4. | fis'4. fis'4 a'8 | a'4 g'8 g'4. | b4. c'4 d'8 | e'4 e'8 d'4. | d'4( g'8) fis'4! fis'8 | g'2.
"""

[parts.Tenor]
choral_type = "tenor"
clef = "bass"
staff_number = 2
notes = """
g4. g4 g8 | g4. g4. | b4. d'4 d'8 | d'2. | g4. g4 g8 | g4. g4. | fis4. g4 fis8 | g2. | g4. g4 g8 | g4 g8 g4. | a4. d'4 d'8 | d'4 d'8 d'4. | g4. g4 g8 | g4 g8 g4. | g4( b8) d'4! c'8 | b2.
"""

[parts.Bass]
choral_type = "bass"
clef = "bass"
staff_number = 2
notes = """
g4. g4 g8 | g4. g4. | e4. d4 d8 | g2. | g4. g4 g8 | g4. g4. | d4. d4 d8 | g,2. | c4. c4 e8 | g4 g8 g4. | d4. d4 fis8 | g4 g8 g4. | g,4. a,4 b,8 | c4 c8 g,4. | d4. d4! d8 | g,2.
"""

[lyrics.1]
text = "“Al -- most per -- suad -- ed” now to be -- lieve; “Al -- most per -- suad -- ed” Christ to re -- ceive; Seems now some soul to say, “Go, Spir -- it, go Thy way, Some more con -- ven -- ient day On Thee I’ll call.”"

[lyrics.2]
text = "“Al -- most per -- suad -- ed,” come, come to -- day; “Al -- most per -- suad -- ed,” turn not a -- way; Je -- sus in -- vites you here, An -- gels are ling’r -- ing near Prayers rise from hearts so dear; O wand -- ’rer, come!"

[lyrics.3]
text = "“Al -- most per -- suad -- ed,” har -- vest is past! “Al -- most per -- suad -- ed,” doom comes at last! “Al -- most” can -- not a -- vail; “Al -- most” is but to fail! Sad, sad, that bit -- ter wail— “Al -- most,” but lost!"
