title = "\"Come!\" 'Tis Jesus Gently Calling"
subtitle = ""
copyrights = [
  "Lyrics: Annie S. Ormsby, 1874 (public domain)",
  "Music: William J. Kirkpatrick, 1882 (public domain)",
  "Arrangement by OpenPsalm, 2026 and released under the CC-BY 4.0 license",
]
key_signature = "Ab"
time_sig_numerator = 4
time_sig_denominator = 4
tempo_bpm = 90
verse_count = 4
phrase_breaks = ["4:64", "8:64", "12:64"]

[parts.Soprano]
choral_type = "soprano"
clef = "treble"
staff_number = 1
notes = """
c''4 bes'4 aes'4. g'8 | f'4 aes'4 f'4 ees'4 | aes'4 c''4 ees''4. c''8 | bes'4 aes'4 bes'2 |
c''4 bes'4 aes'4. g'8 | f'4 aes'4 f'4 ees'4 | aes'4 c''4 f'4. bes'8 | aes'4 g'4 aes'2 |
c''4 ees''4 ees''4 c''4 | bes'4 aes'4 c''4 bes'4 | c''4 ees''4 ees''4. c''8 | bes'4 aes'4 bes'2 |
c''4 bes'4 aes'4 ees'4 | des''4. f'8 f'4 ees'4 | aes'4 c''4 f'4. bes'8 | aes'4 g'4 aes'2 |
"""

[parts.Alto]
choral_type = "alto"
clef = "treble"
staff_number = 1
notes = """
ees'4 des'4 c'4. ees'8 | des'4 des'4 des'4 c'4 | ees'4 aes'4 aes'4. aes'8 | ees'4 d'4 ees'2 |
ees'4 des'4 c'4. ees'8 | des'4 des'4 des'4 c'4 | c'4 ees'4 des'4. f'8 | ees'4 ees'4 ees'2 |
aes'4 aes'4 aes'4 aes'4 | g'4 f'4 aes'4 g'4 | aes'4 aes'4 aes'4. aes'8 | ees'4 d'4 ees'2 |
ees'4 des'4 c'4 c'4 | f'4. des'8 des'4 c'4 | c'4 ees'4 des'4. f'8 | ees'4 ees'4 ees'2 |
"""

[parts.Tenor]
choral_type = "tenor"
clef = "bass"
staff_number = 2
notes = """
aes4 ees4 ees4. aes8 | aes4 aes4 aes4 aes4 | c'4 ees'4 c'4. ees'8 | ees'4 bes4 g2 |
aes4 ees4 ees4. aes8 | aes4 aes4 aes4 aes4 | ees4 aes4 aes4. des'8 | c'4 bes4 c'2 |
ees'4 c'4 c'4 ees'4 | des'4 c'4 ees'4 ees'4 | ees'4 c'4 c'4. ees'8 | ees'4 bes4 g2 |
aes4 ees4 ees4 aes4 | aes4. aes8 aes4 aes4 | ees4 aes4 aes4. des'8 | c'4 bes4 c'2 |
"""

[parts.Bass]
choral_type = "bass"
clef = "bass"
staff_number = 2
notes = """
aes,4 aes,4 aes,4. c8 | des4 f4 aes4 aes4 | aes4 aes4 aes4. aes8 | g4 f4 ees2 |
aes,4 aes,4 aes,4. c8 | des4 f4 aes4 aes4 | aes,4 aes,4 des4. des8 | ees4 ees4 aes,2 |
aes4 aes4 aes4 aes4 | ees4 f4 ees4 ees4 | aes4 aes4 aes4. aes8 | g4 f4 ees2 |
aes,4 aes,4 aes,4 aes,4 | des4. des8 aes,4 aes,4 | aes,4 aes,4 des4. des8 | ees4 ees4 aes,2 |
"""

[lyrics.1]
text = "\"Come!\" 'tis Je -- sus gen -- tly call -- ing, Ye with care and toil op -- pressed, With your guilt how -- e'er ap -- pall -- ing— Come, and I will give you rest. For your sin He once has suf -- fered, On the cross the work was done, And the word by God now ut -- tered To each wear -- y soul is \"Come!\""

[lyrics.2]
text = "\"Come!\" the Fa -- ther's house stands o -- pen, With its love and light and song; And re -- turn -- ing to that Fa -- ther, All to you may now be -- long. From sin's dis -- tant land of fam -- ine, Toil -- ing neath the mid -- day sun, To a Fa -- ther's house of plen -- ty, And a Fa -- ther's wel -- come, \"Come!\""

[lyrics.3]
text = "\"Come!\" for night is gath -- 'ring quick -- ly O'er the world's fast -- fleet -- ing day; If you lin -- ger till the dark -- ness You will sure -- ly miss your way. And still wait -- ing— sad -- ly wait -- ing, Till the day its course has run, With His pa -- tience un -- a -- ba -- ting Je -- sus lin -- gers for you— \"Come!\""

[lyrics.4]
text = "\"Come!\" for an -- gel hosts are mus -- ing O'er this sight so strange -- ly sad: God be -- seech -- ing— man re -- fus -- ing To be made for -- ev -- er glad! From the world and its de -- lu -- sion Now our voi -- ces rise as one; While we shout God's in -- vi -- ta -- tion, Heav'n it -- self re -- ech -- oes \"Come!\""
