title = "All People That on Earth Do Dwell"
subtitle = ""
copyrights = [
  "Lyrics: William Kethe, 1561 (public domain)",
  "Music: 'Old Hundredth' by Louis Bourgeois, 1551 (public domain)",
  "Arrangement by OpenPsalm, 2026 and released under the CC-BY 4.0 license",
]
key_signature = "G"
time_sig_numerator = 4
time_sig_denominator = 4
tempo_bpm = 112
verse_count = 4
phrase_breaks = ["4:32", "7:32", "10:32"]

[parts.Soprano]
choral_type = "soprano"
clef = "treble"
staff_number = 1
notes = """
s2 g'2 | g'4 fis'4 e'4 d'4 | g'2 a'2 | b'2 b'2 |
b'4 b'4 a'4 g'4 | c''2 b'2 | a'2 g'2 | a'4 b'4 a'4 g'4 |
e'2 fis'2 | g'2 d''2 | b'4 g'4 a'4 c''4 | b'2 a'2 |
g'2 s2 |
"""

[parts.Alto]
choral_type = "alto"
clef = "treble"
staff_number = 1
notes = """
s2 d'2 | d'4 d'4 b4 b4 | b2 d'2 | d'2 d'2 |
d'4 g'4 fis'4 g'4 | g'2 g'2 | fis'2 g'2 | fis'4 g'4 fis'4 d'4 |
e'2 d'2 | d'2 d'2 | d'4 g'4 fis'4 e'8[ fis'8] | g'2 fis'2 |
g'2 s2 |
"""

[parts.Tenor]
choral_type = "tenor"
clef = "bass"
staff_number = 2
notes = """
s2 b2 | b4 a4 g4 fis4 | e2 fis2 | g2 g2 |
b4 d'4 d'4 b4 | e'2 d'2 | d'2 b2 | d'4 d'4 d'4 d'4 |
c'4( b4) a2 | b2 b2 | g4 b4 d'4 e'4 | d'2 d'4( c'4) |
b2 s2 |
"""

[parts.Bass]
choral_type = "bass"
clef = "bass"
staff_number = 2
notes = """
s2 g2 | g4 d4 e4 b,4 | e2 d2 | g,2 g2 |
g4 g4 d4 e4 | c2 g,2 | d2 e2 | d4 g4 d4 b,4 |
c2 d2 | g,2 g2 | g4 e4 d4 a,4 | b,4( c4) d2 |
g,2 s2 |
"""

[lyrics.1]
text = "All peo -- ple that on earth do dwell, Sing to the Lord with cheer -- ful voice; Him serve with fear, His praise forth tell: Come ye be -- fore Him and re -- joice."

[lyrics.2]
text = "The Lord ye Know is God in -- deed, With -- out our aid He did us make: We are His flock, He doth us feed, And for His sheep He doth us take."

[lyrics.3]
text = "O en -- ter then His gates with praise, Ap -- proach with joy His courts un -- to: Praise, laud, and bless His name al -- ways, For it is seem -- ly so to do."

[lyrics.4]
text = "For why? The Lord our God is good, His mer -- cy is for -- ev -- er sure: His truth at all times firm -- ly stood, And shall from age to age en -- dure."
