title = "If You Should Look to Kolob"
copyrights = [
  "Lyrics: Jon Hood, 2026 (CC-BY 4.0)",
  "Music: English Folk Tune 'Kingsfold' (public domain)",
  "Arrangement by OpenPsalm, 2026 and released under the CC-BY 4.0 license",
]
key_signature = "G"
time_sig_numerator = 4
time_sig_denominator = 4
verse_count = 4
phrase_breaks = ["5:48", "9:48", "13:48", "17:48"]

[parts.Soprano]
choral_type = "soprano"
clef = "treble"
staff_number = 1
notes = """
s2. g'8[ fis'8] | e'4 e'4 e'4 d'4 | g'2 a'4 g'8[ a'8] | b'4 b'4 a'8[ g'8] e'4 | d'2. g'8[ fis'8] | e'4 e'4 e'4 d'4 | g'4 g'4 a'4 g'8[ a'8] | b'4 b'4 a'8[ g'8] e'4 | e'2. b'8[ c''8] | d''4 b'4 b'8[ a'8] g'4 | a'4-( a'4-) b'4 g'8[ a'8] | b'4 b'8[ a'8] g'4 e'4 | d'2. g'8[ fis'8] | e'4 e'4 e'8[ d'8] e'8[ fis'8] | g'2 a'4 g'8[ a'8] | b'4 b'4 a'8[ g'8] e'4 | e'2. s4
"""

[parts.Alto]
choral_type = "alto"
clef = "treble"
staff_number = 1
notes = """
s2. e'4 | b4 b4 c'4 a4 | d'4( b4) d'4 d'8[ fis'8] | g'4 g'4 e'4 c'4 | a2. d'4 | d'4 c'4 c'8[ b8] a4 | d'4 cis'4 d'4 d'8[ c'8] | b4 d'4 c'4 c'4 | b2. e'4 | fis'4 fis'4 g'8[ d'8] d'4 | e'4-( d'4-) d'4 d'8[ fis'8] | g'4 g'8[ fis'8] d'4 c'8[ b8] | a2. d'4 | d'4 c'4 c'4 c'4 | d'4.( cis'8) d'4 d'8[ c'8] | b4 d'4 e'4 c'4 | b2. s4
"""

[parts.Tenor]
choral_type = "tenor"
clef = "bass"
staff_number = 2
notes = """
s2. b8[ a8] | g4 g4 g4 fis4 | g2 fis4 g8[ c'8] | b4 d'4 c'4 g4 | g2( fis4) g4 | g4 g4 g4 fis4 | g4 g4 fis4 g8[ fis8] | g4 g4 e4 e8[ fis8] | g2. g4 | b4 d'4 d'8[ c'8] b4 | a8-([ g8] fis4-) g4 d'8[ c'8] | d'4 d'8[ c'8] b4 g4 | g2( fis4) g4 | g4 g4 a4 c'4 | b8( a8 g4) fis4 g8[ fis8] | g4 fis4 e4 e8[ fis8] | g2. s4
"""

[parts.Bass]
choral_type = "bass"
clef = "bass"
staff_number = 2
notes = """
s2. e4 | e4 e8[ d8] c4 c4 | b,4( e4) d4 b,8[ a,8] | g,4 g,4 a,4 c4 | d2. b,4 | c4 c8[ b,8] a,4 d4 | b,4 e4 d8[ c8] b,8[ a,8] | g,4 b,4 c4 a,4 | e2. e4 | b,4 b4 e8[ fis8] g4 | c4-( d4-) g,4 b,8[ a,8] | g,4 g,8[ a,8] b,4 c4 | d2. b,4 | c4 c8[ b,8] a,4 a4 | g8( fis8 e4) d4 b,8[ a,8] | g,4 b,4 c4 a,4 | e2. s4
"""

[lyrics.1]
text = "If you should look to Ko -- lob, To find a god in space, Who start -- ed as a sin -- ful man, And had to grow in grace; You will not find the Ma -- _ ker, Who framed the star -- ry sky, Who au -- thored space and mat -- ter, The Sov -- 'reign Lord Most High."

[lyrics.2]
text = "From no -- thing -- ness He formed earth, Be -- fore the world be -- gan, The un -- cre -- a -- ted Great I AM, Whose Son then came as man. He did not earn His glo -- _ ry, He did not have to strive, He spoke all in -- to be -- ing, And brought the stars a -- live."

[lyrics.3]
text = "These a -- lien gods of Ko -- lob, Are fa -- bles made by men, To turn our hearts from ser -- ving Him, Who died and rose a -- gain. For ev -- ery knee is bow -- _ ing, And ev -- ery tongue will claim, The true God of all the earth, And praise His ho -- ly name."

[lyrics.4]
text = "There is no grand pro -- gres -- sion, There is but one main Throne, We wor -- ship the Cre -- a -- tor God, We wor -- ship Him a -- lone. No end -- less line of de -- it -- ies, Through all e -- ter -- ni -- ty, The One, Ho -- ly, Sov -- 'reign Lord, Who was, and is to be."
