title = "Dear Lord and Father of Mankind"
subtitle = ""
key_signature = "Db"
time_sig_numerator = 4
time_sig_denominator = 4
tempo_bpm = 80
verse_count = 6
optional_phrase_breaks = ["3:48", "7:48"]
phrase_breaks = ["5:48", "9:48"]
copyrights = [
  "Lyrics: John Greenleaf Whittier, 1872 (public domain)",
  "Music: 'Rest' by Frederick Charles Maker, 1887 (public domain)",
  "Arrangement by OpenPsalm, 2026 and released under the CC-BY 4.0 license",
]

[parts.Soprano]
choral_type = "soprano"
clef = "treble"
staff_number = 1
notes = """
s2. f'4 | f'4. f'8 e'4 f'4 | aes'4 aes'4 g'4 ges'4 | f'4. des'8 des'4 ees'4 | ees'2. f'4 | f'4. ges'8 aes'4 des''4 | des''4. c''8 bes'4 bes'4 | bes'4. aes'8 ges'4 g'4 | aes'4 ges'4 f'4 aes'4 | des'4. des'8 des'4 ees'4 | f'2. s4
"""

[parts.Alto]
choral_type = "alto"
clef = "treble"
staff_number = 1
notes = """
s2. des'4 | des'4. des'8 des'4 des'4 | des'4 des'4 des'4 ees'4 | des'4. des'8 des'4 des'4 | c'2. des'4 | des'4. c'8 des'4 des'4 | ees'4. ees'8 des'4 des'4 | des'4. d'8 ees'4 ees'4 | ees'4 ees'4 des'4 des'4 | des'4. des'8 des'4 c'4 | des'2. s4
"""

[parts.Tenor]
choral_type = "tenor"
clef = "bass"
staff_number = 2
notes = """
s2. aes4 | aes4. aes8 g4 aes4 | aes4 aes4 bes4 aes4 | aes4. f8 f4 g4 | aes2. aes4 | aes4. aes8 aes4 aes4 | a4. a8 bes4 bes4 | bes4. bes8 bes4 bes4 | aes4 aes4 aes4 ces'4 | ces'4. bes8 bes4 a4 | aes2. s4
"""

[parts.Bass]
choral_type = "bass"
clef = "bass"
staff_number = 2
notes = """
s2. des4 | des4. des8 des4 des4 | f4 f4 ees4 c4 | des4. des8 bes,4 bes,4 | aes,2. des4 | des4. ees8 f4 f4 | f4. f8 ges4 ges4 | ges4. f8 ees4 des4 | c4 c4 des4 f4 | ges4. ges8 ges4 ges4 | des2. s4
"""

[lyrics.1]
text = "Dear Lord and Fa -- ther of man -- kind, For -- give our fool -- ish ways! Re -- clothe us in our right -- ful mind, In pur -- er lives Thy serv -- ice find, In deep -- er rev -- 'rence, praise."

[lyrics.2]
text = "In sim -- ple trust like theirs who heard Be -- side the Syr -- ian sea The gra -- cious call -- ing of the Lord, Let us, like them, with -- out a word Rise up and fol -- low Thee."

[lyrics.3]
text = "O Sab -- bath rest by Gal -- i -- lee! O calm of hills a -- bove, Where Je -- sus knelt to share with Thee The si -- lence of e -- ter -- ni -- ty, In -- ter -- pret -- ed by love!"

[lyrics.4]
text = "With that deep hush sub -- du -- ing all Our words and works that drown The ten -- der whis -- per of Thy call, As noise -- less let Thy bless -- ing fall As fell Thy man -- na down."

[lyrics.5]
text = "Drop Thy still dews of qui -- et -- ness, Till all our striv -- ings cease; Take from our souls the strain and stress, And let our or -- dered lives con -- fess The beau -- ty of Thy peace."

[lyrics.6]
text = "Breathe through the heats of our de -- sire Thy cool -- ness and Thy balm; Let sense be dumb, let flesh re -- tire; Speak through the earth -- quake, wind and fire, O still small voice of calm!"
