title = "Dear Lord and Father of Mankind"
subtitle = "Rest"
key_signature = "D"
time_sig_numerator = 4
time_sig_denominator = 4
tempo_bpm = 80
verse_count = 5
optionql_phrase_breaks = ["3:48", "7:48"]
phrase_breaks = ["5:48", "9:48"]
copyrights = [
  "Lyrics: John Greenleaf Whittier, 1872 (public domain)",
  "Music: 'Rest' by Frederick Charles Maker, 1887 (public domain)",
  "Arrangement by OpenPsalm, 2026 and released under the CC-BY 4.0 license",
]

[parts.Soprano]
choral_type = "soprano"
clef = "treble"
staff_number = 1
notes = """
s2. fis'4 | fis'4. fis'8 eis'4 fis'4 | a'4 a'4 gis'4 g'4 | fis'4. d'8 d'4 e'4 | e'2. fis'4 | fis'4. g'8 a'4 d''4 | d''4. cis''8 b'4 b'4 | b'4. a'8 g'4 gis'4 | a'4 g'4 fis'4 a'4 | d'4. d'8 d'4 e'4 | fis'2. s4
"""

[parts.Alto]
choral_type = "alto"
clef = "treble"
staff_number = 1
notes = """
s2. d'4 | d'4. d'8 d'4 d'4 | d'4 d'4 d'4 e'4 | d'4. d'8 d'4 d'4 | cis'2. d'4 | d'4. cis'8 d'4 d'4 | e'4. e'8 d'4 d'4 | d'4. dis'8 e'4 e'4 | e'4 e'4 d'4 d'4 | d'4. d'8 d'4 cis'4 | d'2. s4
"""

[parts.Tenor]
choral_type = "tenor"
clef = "bass"
staff_number = 2
notes = """
s2. a4 | a4. a8 gis4 a4 | a4 a4 b4 a4 | a4. fis8 fis4 gis4 | a2. a4 | a4. a8 a4 a4 | ais4. ais8 b4 b4 | b4. b8 b4 b4 | a4 a4 a4 c'4 | c'4. b8 b4 bes4 | a2. s4
"""

[parts.Bass]
choral_type = "bass"
clef = "bass"
staff_number = 2
notes = """
s2. d4 | d4. d8 d4 d4 | fis4 fis4 e4 cis4 | d4. d8 b,4 b,4 | a,2. d4 | d4. e8 fis4 fis4 | fis4. fis8 g4 g4 | g4. fis8 e4 d4 | cis4 cis4 d4 fis4 | g4. g8 g4 g4 | d2. s4
"""

[lyrics.1]
text = "Dear Lord and Fa -- ther of man -- kind, For -- give our fool -- ish ways! Re -- clothe us in our right -- ful mind; In pur -- er lives Thy serv -- ice find, In deep -- er rev -- 'rence, praise."

[lyrics.2]
text = "In sim -- ple trust like theirs who heard, Be -- side the Syr -- ian sea, The gra -- cious call -- ing of the Lord, Let us, like them, with -- out a word Rise up and fol -- low Thee."

[lyrics.3]
text = "O Sab -- bath rest by Gal -- i -- lee! O calm of hills a -- bove, Where Je -- sus knelt to share with Thee The si -- lence of e -- ter -- ni -- ty, In -- ter -- pret -- ed by love!"

[lyrics.4]
text = "Drop Thy still dews of qui -- et -- ness, Till all our striv -- ings cease; Take from our souls the strain and stress, And let our or -- dered lives con -- fess The beau -- ty of Thy peace."

[lyrics.5]
text = "Breathe through the heats of our de -- sire Thy cool -- ness and Thy balm; Let sense be dumb, let flesh re -- tire; Speak through the earth -- quake, wind and fire, O still small voice of calm!"
