title = "The Name of Jesus"
copyrights = [
  "Lyrics: William C. Martin, 1901 (public domain)",
  "Music: Edmund S. Lorenz, 1901 (public domain)",
  "Arrangement by OpenPsalm, 2026 and released under the CC-BY 4.0 license",
]
key_signature = "C"
time_sig_numerator = 3
time_sig_denominator = 4
tempo_bpm = 100
verse_count = 4
phrase_breaks = ["5:32", "9:48", "13:48"]
optional_phrase_breaks = ["3:32", "7:24", "11:48", "15:24"]
non_breaking_phrase_breaks = ["8:32", "16:32"]

[parts.Soprano]
choral_type = "soprano"
clef = "treble"
staff_number = 1
notes = """
s2 g'4 | c''8 b'8 a'4. e'8 | g'8 fis'8 f'4 b'4 | d''8 c''8 b'4. f'8 | a'8 g'8 g'4 c''4 | e''8 d''8 c''4. b'8 | b'8 a'8 a'8! a'8 b'8 c''8 | d''2 e''4 | d''4 g'2 | c''4@c g'4 a'8 g'8 | g'8 f'8 f'2 | d''4 b'4 c''8 b'8 | a'8 g'8 g'2 | e''4 c''4 d''8 c''8 | b'8 a'8 a'8 a'8 b'8 c''8 | e''2 c''4 | d''4! c''4 s4
"""

[parts.Alto]
choral_type = "alto"
clef = "treble"
staff_number = 1
suppress_verses = [2, 3, 4]
suppress_verses_when = ["soprano"]
notes = """
s2 e'4 | e'8 e'8 e'4. e'8 | e'8 dis'8 d'4 f'4 | f'8 e'8 f'4. f'8 | f'8 e'8 e'4 e'4 | g'8 f'8 e'4. d'8 | d'8 c'8 f'8! r8 r8 f'8 | fis'8 g'8 a'4 fis'4 | f'4 f'2 | e'4@c e'4 f'8 e'8 | e'8 d'8 d'2 | f'4 f'4 f'8 f'8 | f'8 e'8 e'2 | g'4 e'4 f'8 e'8 | d'8 c'8 f'8 r8 r8 a'8 | g'8 c''8 g'4 e'4 | f'4! e'4 s4
"""

[parts.Tenor]
choral_type = "tenor"
clef = "bass"
staff_number = 2
suppress_verses = [2, 3, 4]
suppress_verses_when = ["soprano"]
notes = """
s2 g4 | g8 gis8 a4. a8 | b8 b8 b4 d'4 | b8 c'8 d'4. b8 | c'8 c'8 c'4 g4 | c'8 g8 g4. gis8 | gis8 a8 c'8! r8 r8 a8 | a8 b8 c'4 c'4 | b4 b2 | g4@c c'4 c'8 c'8 | b8 b8 b2 | b4 d'4 d'8 d'8 | c'8 c'8 c'2 | c'4 g4 g8 g8 | gis8 a8 c'8 r8 r8 c'8 | c'8 c'8 c'4 c'4 | b4! c'4 s4
"""

[parts.Bass]
choral_type = "bass"
clef = "bass"
staff_number = 2
suppress_verses = [2, 3, 4]
suppress_verses_when = ["soprano"]
notes = """
s2 c4 | c8 c8 c4. c8 | d8 d8 d4 g4 | g8 g8 g4. g8 | c8 c8 c4 c4 | c8 c8 c4. e8 | f8 f8 f8! r8 r8 f8 | d8 d8 d4 d4 | g4 g2 | c4@c c4 c8 c8 | g8 g8 g2 | g4 g4 g8 g8 | c8 c8 c2 | c4 c4 c8 c8 | e8 f8 f8 r8 r8 f8 | g8 g8 g4 g4 | g4! c4 s4
"""

[lyrics.1]
text = "The name of Je -- sus is so sweet, I love its mu -- sic to re -- peat; It makes my joys full and com -- plete, The pre -- cious name of Je -- sus!"

[lyrics.2]
text = "I love the name of Him whose heart Knows all my griefs and bears a part; Who bids all anx -- ious fears de -- part, I love the name of Je -- sus!"

[lyrics.3]
text = "That name I fond -- ly love to hear, It nev -- er fails my heart to cheer; Its mu -- sic dries the fall -- ing tear, Ex -- alt the name of Je -- sus!"

[lyrics.4]
text = "No word of man can ev -- er tell How sweet the name I love so well; Oh, let its prais -- es ev -- er swell, Oh, praise the name of Je -- sus!"

[lyrics.chorus]
text = "“Je -- sus,” oh, how sweet the name! “Je -- sus,” ev -- ery day the same; “Je -- sus,” let all saints pro -- claim Its wor -- thy praise for -- ev -- er!"
