title = "Majestic Sweetness Sits Enthroned"
verse_count = 4
key_signature = "G"
time_sig_numerator = 6
time_sig_denominator = 4
tempo_bpm = 150
phrase_breaks = ["5:80", "9:80"]
copyrights = [
  "Lyrics: Samuel Stennett, 1787 (public domain)",
  "Music: 'Ortonville' by Thomas Hastings, 1837 (public domain)",
  "Courtesy of the [Cyber Hymnal™](http://www.hymntime.com/tch)",
  "Arrangement by OpenPsalm, 2026 and released under the CC-BY 4.0 license",
]
optional_phrase_breaks = ["3:80", "7:80"]

[parts.Soprano]
choral_type = "soprano"
clef = "treble"
staff_number = 1
notes = """
s2. s2 d'4 | g'2 g'4 a'2 a'4 | b'2 a'4 g'2 d'4 | e'2 e'4 g'2 e'4 | d'2.~ d'2 d'4
| g'2 g'4 a'2 a'4 | b'2 c''4 d''2 b'8[ a'8] | g'2 g'4 a'2 a'4 | g'2.~ g'2 g'4
| b'2 b'4 a'2 a'4 | g'2.~ g'2 s4
"""

[parts.Alto]
choral_type = "alto"
clef = "treble"
staff_number = 1
notes = """
s2. s2 b4 | d'2 d'4 d'2 d'4 | d'2 c'4 b2 b4 | c'2 c'4 e'2 c'4 | b2.~ b2 b4
| d'2 d'4 d'2 d'4 | d'2 d'4 d'2 d'8[ c'8] | b2 b4 c'2 c'4 | b2.~ b2 b4
| d'2 d'4 d'2 c'4 | b2.~ b2 s4
"""

[parts.Tenor]
choral_type = "tenor"
clef = "bass"
staff_number = 2
notes = """
s2. s2 g4 | g2 g4 fis2 fis4 | g2 fis4 g2 g4 | g2 g4 g2 g4 | g2.~ g2 g4
| g2 g4 fis2 fis4 | g2 a4 b2 g4 | d2 d4 d2 d4 | d2.~ d2 g4
| g2 g4 fis2 fis4 | g2.~ g2 s4
"""

[parts.Bass]
choral_type = "bass"
clef = "bass"
staff_number = 2
notes = """
s2. s2 g,4 | b,2 b,4 d2 d4 | g2 d4 g,2 g,4 | c2 c4 c2 c4 | g,2.~ g,2 g,4
| b,2 b,4 d2 d4 | g2 g4 g2 g,4 | g,2 g,4 d2 d4 | g,2.~ g,2 g,4
| g2 g4 d2 d4 | g,2.~ g,2 s4
"""

[lyrics.1]
text = "Ma -- jes -- tic sweet -- ness sits en -- throned, Up -- on the Sav -- ior's brow; His head with ra -- diant glo -- ries crowned, His lips with grace o'er -- flow, His lips with grace o'er -- flow."

[lyrics.2]
text = "No mor -- tal can with Him com -- pare, A -- mong the sons of men; Fair -- er is He than all the fair, Who fill the heav'n -- ly train, Who fill the heav'n -- ly train."

[lyrics.3]
text = "He saw me plunged in deep dis -- tress, And flew to my re -- lief; For me He bore the shame -- ful cross, And car -- ried all my grief, And car -- ried all my grief."

[lyrics.4]
text = "To Him I owe my life and breath, And all the joys I have; He makes me tri -- umph o -- ver death, And saves me from the grave, And saves me from the grave."
