title = "Awake, and Sing the Song"
subtitle = "St. Thomas"
copyrights = [
  "Lyrics: William Hammond, 1745 (public domain)",
  "Music: 'St. Thomas' by Aaron Williams, 1770 (public domain)",
  "Arrangement by OpenPsalm, 2026 and released under the CC-BY 4.0 license",
]
commentary = "<p>This same hymn text is also available set to the tune <a href=\"/songs/65\">Silver Street</a>.</p>"
key_signature = "G"
time_sig_numerator = 4
time_sig_denominator = 4
verse_count = 4
tempo_bpm = 96
phrase_breaks = ["5:48"]

[parts.Soprano]
choral_type = "soprano"
clef = "treble"
staff_number = 1
notes = """
s2. d'4 | g'4 g'4 b'4 a'8[ g'8] | a'2. b'8[ c''8] | d''4 c''8[ b'8] c''4 b'4 | a'2. d''4 | b'4 g'4 a'4 d'4 | g'8[ a'8] b'8[ cis''8] d''4. d''8 | e''4 d''8[ c''8] b'4 a'4 | g'2. s4
"""

[parts.Alto]
choral_type = "alto"
clef = "treble"
staff_number = 1
notes = """
s2. b4 | d'4 d'4 d'4 d'8[ cis'8] | d'2. g'8[ fis'8] | g'4 fis'8[ g'8] e'8[ fis'8] g'4 | fis'2. d'4 | d'4 d'4 d'4 d'4 | d'4 g'4 fis'4. g'8 | g'4 g'4 g'4 fis'4 | d'2. s4
"""

[parts.Tenor]
choral_type = "tenor"
clef = "bass"
staff_number = 2
notes = """
s2. g4 | g4 b4 d'4 a4 | fis2. d'4 | d'4 d'4 c'4 d'4 | d'2. a4 | g4 g4 fis4 a4 | b4 g4 a4. b8 | c'4 d'8[ e'8] d'4 c'4 | b2. s4
"""

[parts.Bass]
choral_type = "bass"
clef = "bass"
staff_number = 2
notes = """
s2. g,4 | b,4 g,4 g4 fis8[ e8] | d2. g8[ a8] | b4 a8[ g8] a4 g4 | d2. fis4 | g4 b,4 d4 fis4 | g4 e4 d4. g8 | c4 b,8[ c8] d4 d4 | g,2. s4
"""

[lyrics.1]
text = "A -- wake, and sing the song Of Mo -- ses and the Lamb; Tune eve -- ry heart and eve -- ry tongue To praise the Sa -- vior's name."

[lyrics.2]
text = "Sing of His dy -- ing love; Sing of His ris -- ing power; Sing how He in -- ter -- cedes a -- bove For those whose sins He bore."

[lyrics.3]
text = "Tell, in se -- ra -- phic strains, What He has done for you; How He has tak -- en off your chains And formed your hearts a -- new."

[lyrics.4]
text = "His faith -- ful -- ness pro -- claim While life to you is given: Join hands and hearts to praise His name Till we all meet in heav'n."
