title = "His Love Is Mine"
subtitle = ""
copyrights = [
  "Lyrics: Thomas O. Chisholm, 1926 (public domain)",
  "Music: Charles H. Gabriel, 1926 (public domain)",
  "Arrangement by OpenPsalm, 2026 and released under the CC-BY 4.0 license",
]
key_signature = "F"
time_sig_numerator = 3
time_sig_denominator = 4
tempo_bpm = 96
verse_count = 4
optional_phrase_breaks = ["3:40", "7:40", "11:24", "15:24"]
phrase_breaks = ["5:32", "9:24", "13:24"]
commentary = """
<p>These same lyrics are also set to entirely different music by James Williams in the same 1926 collection, <em>Sweeter Than All Songs</em> (Gospel Advocate
Co., 1926) under the title <a href="/songs/115">What Need I More</a>.</p>
"""

[parts.Soprano]
choral_type = "soprano"
clef = "treble"
staff_number = 1
notes = """
s2 c'4 | f'8. g'16 a'4. a'8 | bes'8. bes'16 a'4. a'8 | c''8 bes'8 a'8 g'8 f'8 e'8 |
f'2 f'4 | g'8. a'16 g'4. c'8 | f'8. g'16 a'4. a'8 | c''8 d''8 c''8 g'8 a'8! g'8 |
f'4. f'8@c d''8. d''16 | d''4. bes'8 f''8. f''16 | c''4. a'8 c''8. c''16 | c''4. c''8 d''8. f''16 |
e''4. c''8 c''8. c''16 | f''4. c''8 bes'8 a'8 | g'4. f''8 e''8 d''8 | c''8 g'8 a'4. g'8 |
f'2 s4 |
"""

[parts.Alto]
choral_type = "alto"
clef = "treble"
staff_number = 1
notes = """
s2 c'4 | c'8. c'16 f'4. f'8 | f'8. f'16 f'4. f'8 | f'8 f'8 f'8 c'8 c'8 c'8 |
c'2 bes4 | e'8. f'16 e'4. c'8 | bes8. e'16 f'4. f'8 | f'8 f'8 f'8 f'8 f'8! c'8 |
c'4. f'8@c f'8. f'16 | f'4. f'8 f'8. f'16 | f'4. f'8 dis'8. dis'16 | e'4. e'8 g'8. g'16 |
g'4. g'8 f'8. bes'16 | a'4. f'8 f'8 f'8 | f'4. f'8 f'8 f'8 | f'8 f'8 f'4. c'8 |
c'2 s4 |
"""

[parts.Tenor]
choral_type = "tenor"
clef = "bass"
staff_number = 2
notes = """
s2 a4 | a8. bes16 c'4. c'8 | bes8. bes16 a4. c'8 | c'8 d'8 c'8 bes8 a8 g8 |
a2 a4 | c'8. c'16 c'4. c'8 | c'8. c'16 c'4. c'8 | a8 bes8 f8 b8 c'8! bes8 |
a4. a8@c bes8. bes16 | bes4. d'8 d'8. bes16 | a4. c'8 a8. a16 | c'4. c'8 b8. d'16 |
c'4. c'8 c'8. c'16 | c'4. a8 bes8 c'8 | d'4. d'8 c'8 bes8 | a8 b8 c'4. bes8 |
a2 s4 |
"""

[parts.Bass]
choral_type = "bass"
clef = "bass"
staff_number = 2
notes = """
s2 f4 | f8. f16 f4. f8 | d8. d16 d4. f8 | a,8 bes,8 c8 c8 c8 c8 |
f2 f4 | c8. c16 c4. bes,8 | a,8. c16 f4. f8 | f8 f8 f8 d8 c8! c8 |
f,4. f8@c bes,8. bes,16 | bes,4. bes,8 bes,8. d16 | f4. f8 fis8. fis16 | g4. g8 g8. g16 |
c'4. bes8 a8. g16 | f4. ees8 d8 c8 | bes,4. bes,8 bes,8 bes,8 | c8 d8 c4. c8 |
f2 s4 |
"""

[lyrics.1]
text = "The love of Je -- sus, 'tis di -- vine, That love so won -- der -- ful is mine; My heart hath to -- kens man -- i -- fold, More dear to me than gems or gold."

[lyrics.2]
text = "For ev -- 'ry step He gives me light, And songs to sing in dark -- est night, He gives me grace in tri -- al's hour And vict -- 'ry o'er the temp -- ter's pow'r."

[lyrics.3]
text = "Each day He send -- eth from a -- bove Some fresh as -- sur -- ance of His love, Some prov -- i -- den -- tial to -- ken true, Some mes -- sage sweet, some mer -- cy new."

[lyrics.4]
text = "But, best of all, Him -- self He gives, With -- in my heart His Spir -- it lives, And wit -- ness bears with mine that He, Who died for oth -- ers, died for me."

[lyrics.chorus]
text = "My cup is full! It run -- neth o'er! His love is mine, what need I more? I dwell be -- neath His shel -- t'ring wing And trust Him, now, for ev -- 'ry -- thing."
