title = "Able to Deliver"
subtitle = ""
copyrights = [
  "Lyrics: Fanny J. Crosby, 1899 (public domain)",
  "Music: Ira David Sankey, 1899 (public domain)",
  "Arrangement by OpenPsalm, 2026 and released under the CC-BY 4.0 license",
]
key_signature = "Bb"
time_sig_numerator = 4
time_sig_denominator = 4
tempo_bpm = 105
verse_count = 3
optional_phrae_breaks = ["7:48", "15:48"]
phrase_breaks = ["3:48", "5:48", "9:48", "11:48", "13:48"]

[parts.Soprano]
choral_type = "soprano"
clef = "treble"
staff_number = 1
notes = """
s2. d'8.[ ees'16] | g'4 f'4 f'4 bes'8. c''16 | bes'4 a'4 a'4 c'8. d'16 | ees'4 ees'4 ees'4 a'8. g'16 | g'4 f'4 f'4 d'8. ees'16 | f'4 f'4 f'4 d''8. d''16 | c''4 g'4 g'4 c''8.[ bes'16] | a'4 a'4 bes'4 c''4 | bes'2. f'8.@c bes'16 | d''4 d''4 d''4 ees''8. d''16 | d''4 c''4 c''4 f'8. a'16 | c''4 c''4 c''4 d''8. c''16 | c''4 bes'4 bes'4 f'8. f'16 | g'4 g'4 bes'4 a'8. g'16 | f'4 bes'4 d''4 bes'4 | c''4 g'4 a'4. f'8 | bes'1
"""

[parts.Alto]
choral_type = "alto"
clef = "treble"
staff_number = 1
notes = """
s2. bes8.[ c'16] | ees'4 d'4 d'4 f'8. ees'16 | d'4 c'4 c'4 a8. bes16 | c'4 c'4 c'4 ees'8. ees'16 | d'4 d'4 d'4 bes8. c'16 | d'4 d'4 d'4 f'8. f'16 | ees'4 ees'4 ees'4 e'8.[ g'16] | f'4 ees'4 d'4 ees'4 | d'2. d'8.@c d'16 | f'4 f'4 f'4 g'8. f'16 | f'4 ees'4 ees'4 ees'8. ees'16 | ees'4 ees'4 ees'4 f'8. ees'16 | ees'4 d'4 d'4 d'8. d'16 | ees'4 ees'4 g'4 f'8. ees'16 | d'4 d'4 f'4 f'4 | ees'4 ees'4 ees'4. ees'8 | d'1
"""

[parts.Tenor]
choral_type = "tenor"
clef = "bass"
staff_number = 2
notes = """
s2. f4 | bes4 bes4 bes4 bes8. g16 | f4 f4 f4 f8. f16 | a4 a4 a4 c'8. a16 | bes4 bes4 bes4 f8. g16 | bes4 bes4 bes4 bes8. bes16 | g4 bes4 bes4 c'8.[ c'16] | c'4 c'4 bes4 a4 | bes2. bes8.@c bes16 | bes4 bes4 bes4 bes8. bes16 | a4 a4 a4 a8. c'16 | a4 a4 a4 f8. a16 | bes4 bes4 f4 bes8. bes16 | bes4 bes4 bes4 bes8. bes16 | bes4 f4 bes4 aes4 | g4 c'4 c'4. a8 | f1
"""

[parts.Bass]
choral_type = "bass"
clef = "bass"
staff_number = 2
notes = """
s2. bes,4 | bes,4 bes,4 bes,4 d8. ees16 | f4 f4 f4 f8. f16 | f4 f4 f4 f8. f16 | bes,4 bes,4 bes,4 bes,8. bes,16 | bes,4 bes,4 bes,4 bes,8. bes,16 | ees4 ees4 ees4 c8.[ c16] | f4 f4 f4 f4 | bes,2. bes,8.@c bes,16 | bes,4 bes,4 bes,4 bes,8. bes,16 | f4 f4 f4 f8. f16 | f4 f4 f4 f8. f16 | bes,4 bes,4 bes,4 bes,8. bes,16 | ees4 ees4 ees4 ees8. ees16 | bes,4 bes,4 bes,4 d4 | ees4 ees4 f4. f8 | bes,1
"""

[lyrics.1]
text = "O trou -- bled heart, be thou not a -- fraid, In the Lord thy God, let thy hope be stayed; He will hear thy cry and will give thee aid, What -- e'er thy cross may be."

[lyrics.2]
text = "O trou -- bled heart, tho' thy foes u -- nite, Let thy faith be strong and thy ar -- mor bright; Thou shalt o -- ver -- come thro' His pow'r and might, And more than con -- qu'ror be."

[lyrics.3]
text = "O trou -- bled heart, when thy way is drear, He will res -- cue thee and dis -- pel thy fear; In thy great -- est need He is al -- ways near, To Him all glo -- ry be."

[lyrics.chorus]
text = "He is a -- ble still to de -- liv -- er thee, And His own right -- hand thy de -- fence shall be: He is a -- ble still to de -- liv -- er thee, Then be thou not a -- fraid."
