title = "Let the Song Go 'Round the Earth"
verse_count = 5
key_signature = "F"
time_sig_numerator = 4
time_sig_denominator = 4
tempo_bpm = 100
phrase_breaks = ["5:48", "9:64", "13:48"]
optional_phrase_breaks = ["3:64", "7:64", "11:48", "15:64"]
copyrights = [
  "Lyrics: Sarah G. Stock, 1898 (public domain)",
  "Music: J. B. Herbert, 1926 (public domain)",
  "Arrangement by OpenPsalm, 2026 and released under the CC-BY 4.0 license",
]

[parts.Soprano]
choral_type = "soprano"
clef = "treble"
staff_number = 1
notes = """
s2. c'8 c'8 |
f'4 f'4 a'4 c''4\\< |
f''4(\\! d''4 c''4 bes'4) |
a'4 f'4 bes'4 a'4 |
g'2.\\> c'8\\! c'8 |
f'4 f'4 a'4 c''4\\< |
f''4(\\! d''4 c''4 bes'4) |
a'4. bes'8 a'4 g'4 |
f'2.\\> r4\\! |
g'4-.%p fis'4-. g'4-. a'4-. |
bes'4-.\\< a'4-. bes'4-. c''4-. |
d''4-. c''4-. bes'4-. a'4-. |
g'4-. fis'4-. g'4!\\!%f c'8@c c'8 |
f'4 f'4 a'4 c''4\\< |
f''4(\\! d''4 c''4 bes'4) |
a'4. bes'8 a'4 g'4 |
f'2.\\> s4\\!
"""

[parts.Alto]
choral_type = "alto"
clef = "treble"
staff_number = 1
notes = """
s2. c'8 c'8 |
c'4 c'4 f'4 a'4\\< |
a'4(\\! bes'4 a'4 g'4) |
f'4 f'4 e'4 f'4 |
g'4(\\> f'4 e'4) c'8\\! c'8 |
c'4 c'4 f'4 a'4\\< |
a'4(\\! bes'4 a'4 g'4) |
f'4. g'8 f'4 c'4 |
c'2.\\> r4\\! |
e'4-.%p dis'4-. e'4-. f'4-. |
g'4-.\\< fis'4-. g'4-. a'4-. |
bes'4-. a'4-. g'4-. f'4-. |
e'4-. dis'4-. e'4!\\!%f c'8@c c'8 |
c'4 c'4 f'4 a'4\\< |
a'4(\\! bes'4 a'4 g'4) |
f'4. g'8 f'4 c'4 |
c'2.\\> s4\\!
"""

[parts.Tenor]
choral_type = "tenor"
clef = "bass"
staff_number = 2
notes = """
s2. c8 c8 |
a4 a4 c'4 c'4\\< |
c'4(\\! bes4 c'4 d'4) |
c'4 c'4 c'4 c'4 |
c'4(\\> b4 c'4) c8\\! c8 |
a4 a4 c'4 c'4\\< |
c'4(\\! bes4 c'4 d'4) |
c'4. d'8 c'4 bes4 |
a2.\\> r4\\! |
bes4-.%p a4-. bes4-. a4-. |
g4-.\\< a4-. g4-. f4-. |
e4-. f4-. g4-. a4-. |
bes4-. a4-. bes4!\\!%f c8@c c8 |
a4 a4 c'4 c'4\\< |
c'4(\\! bes4 c'4 d'4) |
c'4. d'8 c'4 bes4 |
a2.\\> s4\\!
"""

[parts.Bass]
choral_type = "bass"
clef = "bass"
staff_number = 2
notes = """
s2. c8 c8 |
f4 f4 f4 f4\\< |
f4(\\! g4 a4 bes4) |
c'4 a4 g4 f4 |
e4(\\> d4 c4) c8\\! c8 |
f4 f4 f4 f4\\< |
f4(\\! g4 a4 bes4) |
c'4. c8 d4 e4 |
f2.\\> r4\\! |
c4-.%p c4-. c4-. c4-. |
c4-.\\< c4-. c4-. c4-. |
c4-. c4-. c4-. c4-. |
c4-. c4-. c4!\\!%f c8@c c8 |
f4 f4 f4 f4\\< |
f4(\\! g4 a4 bes4) |
c'4. c8 d4 e4 |
f2.\\> s4\\!
"""

[lyrics.1]
text = "Let the song go 'round the earth, Je -- sus Christ is Lord; Sound His prais -- es, tell His worth, Be His name a -- dored: Ev -- 'ry clime and ev -- 'ry tongue, Come, join the grand, the glo -- rious song,"

[lyrics.2]
text = "Let the song go 'round the earth! From the east -- ern sea, Where the day -- light has its birth, Glad, and bright, and free! Chi -- na's mil -- lions join the strains, And waft them on to In -- dia's plains,"

[lyrics.3]
text = "Let the song go 'round the earth! Lands where Is -- lam's sway, Dark -- ly broods o'er home and hearth, Cast their bonds a -- way! Let His praise from 'Af -- ric's shore Rise, rise and swell her wide lands o'er."

[lyrics.4]
text = "Let the song go 'round the earth! Where the sum -- mer smiles, Let the notes of ho -- ly mirth, Break from dis -- tant isles! In -- land for -- ests, dark and dim, And ice -- bound coasts give back the hymn,"

[lyrics.5]
text = "Let the song go 'round the earth! Je -- sus Christ is King; With the sto -- ry of His worth. Let the whole world ring! Him cre -- a -- tion all a -- dore For ev -- er -- more and ev -- er -- more,"

[lyrics.chorus]
text = "Let the song go 'round the earth, Je -- sus Christ is King!"
